Export SVG icons names
PaackEng/paack-ui-assets pull request #147
Opened 2022-02-17 15:43 UTC by 3imed-jaberi

Create a script to generate SVG icons names based on the "svg" directory which helps us to put all the icons inside the new design system storybook ([Iconghraphy](https://paacklogistics.atlassian.net/browse/DES-137)).

2022-02-17 15:47 UTC, PedroHLC commented on src/utils/getSVGFilename.js
> +})()
any special reason for creating a function, giving it a name, to anonymously invoke her and leave?

2022-02-17 15:47 UTC, PedroHLC commented on package.json
>      "build:parcel": "parcel build src/js/*.js --out-dir ./js",
if you guys want to replace Parcel with any other **bundler**, feel free to open a PR.

2022-02-17 15:50 UTC, 3imed-jaberi commented on package.json
>      "build:parcel": "parcel build src/js/*.js --out-dir ./js",
we don't need to replace the bundler, just we need to copy the generated names to the published directory and in our case, it's the `js` dir.

2022-02-17 15:54 UTC, 3imed-jaberi commented on src/utils/getSVGFilename.js
> +})()
no special reason just to describe what the function does... otherwise, I remove the IIFE.

2022-02-18 07:32 UTC, mtzfactory requested changes

2022-02-18 07:32 UTC, mtzfactory commented on .gitignore
> +src/js/*.json
Why the file with svg name is being ignored?
[It won't get published inside the package](https://docs.npmjs.com/cli/v8/using-npm/developers#keeping-files-out-of-your-package) as there is no `.npmigonore` file

2022-02-18 14:23 UTC, mtzfactory approved these changes

2022-02-18 14:34 UTC, merged