Fix SSR exception issue
PaackEng/paack-ui-assets pull request #165
Opened 2022-04-11 11:44 UTC by Umerbhat

Fixed window exception issue on doing SSR

2022-04-11 12:17 UTC, PedroHLC commented on src/js/paackSvgIconSprite.js
> +if(typeof window === 'undefined'){
are you sure that's what you want? `typeof window` always returns `"object"` for me...

2022-04-11 12:19 UTC, 3imed-jaberi requested changes

2022-04-11 12:19 UTC, 3imed-jaberi commented on src/js/paackSvgIconSprite.js
> +}
What do you think to export function to define this Web Component like this; 
```js
const definePaackSvgIconSprit = () => window.customElements.define('paack-svg-icon-sprite', PaackSvgIconSprite);
```
I think it gives us more flexibility to handle/support SSR, ISR, SSG ... outside of this module [ELM/React].

Also, we should update the condition of the current if statement;

```suggestion
if(typeof window !== 'undefined') window.customElements.define('paack-svg-icon-sprite', PaackSvgIconSprite);
```

2022-04-11 12:24 UTC, PedroHLC commented on src/js/paackSvgIconSprite.js
> +}
for me, that's fine.

2022-04-11 12:59 UTC, mtzfactory commented on src/js/paackSvgIconSprite.js
> +}
Sounds good for me...

2022-04-12 08:14 UTC, Umerbhat commented on src/js/paackSvgIconSprite.js
> +}
@3imed-jaberi I have updated missing not(!) 😓

2022-04-13 07:27 UTC, mtzfactory approved these changes

2022-04-13 11:19 UTC, 3imed-jaberi reviewed
@mtzfactory @PedroHLC @Umerbhat;
Let's make a release here based on this patch update.
One day when we like to change the behavior release a major version by exporting a function to define the element like this; 

```js
const definePaackSvgIconSprit = () => window.customElements.define('paack-svg-icon-sprite', PaackSvgIconSprite);
```

or export only the Web Component class and handle the definition process outside this module which gives us more flexibility to handle the side behaviors (this option is better for me).

2022-04-13 11:20 UTC, 3imed-jaberi approved these changes

2022-04-13 11:47 UTC, merged