WMS-529 | Fix text-ellipsizable for text updates
PaackEng/paack-ui-assets pull request #8
Opened 2020-09-07 16:36 UTC by segmentationfaulter

`text-ellipsizable` was working fine for first renders, but it wasn't handling updates, which was resulting in scenarios like this

![bug](https://user-images.githubusercontent.com/6733537/92406510-a1f42b00-f151-11ea-88d6-4df6958422c6.png)

In this screenshot, you can see that `textContent` of `span.text` different from that `ellipsizable-text`, this was causing the table filters to behave buggy. Changes here are an attempt to fix it.

2020-09-07 17:19 UTC, renanpvaz commented on src/js/ellipsizableText.js
> +    this.textNode.textContent = textContent;
If I understood the bug  then `connectedCallback` is not fired again right? if that's the case maybe this should be done when the attribute changes as well

2020-09-08 07:33 UTC, segmentationfaulter commented on src/js/ellipsizableText.js
> +    this.textNode.textContent = textContent;
Yes, `connectedCallback` fires when our custom element is connected with the DOM, but it doesn't fire when attributes for the element change. I had to switch to receive text contents in an attribute rather than as a child text node, because you can only observe attributes for changes, not the `textContent` of the element.

2020-09-08 12:08 UTC, jouderianjr requested changes

2020-09-08 12:08 UTC, jouderianjr commented on src/js/ellipsizableText.js
> +    const textContent = this.getAttribute(TEXT_ATTRIBUTE);
I don't think this will work as we are not passing the value as a html attribute, we are passing as a text inside the node 🤔 , should we maybe change the way we are implementing? Instead of `<our-tag>blablabla</our-tag>` we use: `<our-tag text="blablabla"></our-tag>` as I don't think we can observe the textContent here. cc @renanpvaz

2020-09-08 12:11 UTC, segmentationfaulter commented on src/js/ellipsizableText.js
> +    const textContent = this.getAttribute(TEXT_ATTRIBUTE);
I have already opened a PR having corresponding change, have a look

https://github.com/PaackEng/paack-ui/pull/92

2020-09-08 12:33 UTC, jouderianjr commented on src/js/ellipsizableText.js
> +    const textContent = this.getAttribute(TEXT_ATTRIBUTE);
🤦  my bad man, I didn't see this, sorry.

I found another problem, once we add the tooltip, we are not removing if it is not needed anymore, so we have to add some logic to remove the tooltip as well.

![Sep-08-2020 14-30-15](https://user-images.githubusercontent.com/1559013/92476977-183f6e80-f1e0-11ea-94d8-258160118398.gif)

2020-09-08 16:04 UTC, segmentationfaulter commented on src/js/ellipsizableText.js
> +    const textContent = this.getAttribute(TEXT_ATTRIBUTE);
Basically it was not only that a tooltip was showing when it was not needed at all, it was also wrong one. Update logic has got a little trickier, actually we needed to remove the tooltip if it pre-existed and text stopped overflowing due to an update.

2020-09-09 09:59 UTC, jouderianjr approved these changes

2020-09-09 09:59 UTC, jouderianjr commented on src/js/ellipsizableText.js
> +  updateTooltip () {
a really small thing, but it's missing the `;` here

2020-09-09 10:09 UTC, merged

2020-09-09 12:28 UTC, PedroHLC reviewed
Tested, debugged, and approved.